### ISSUE TITLE
List of lists or list of numpy arrays for input data

### ISSUE THREAD

**Issue by jonnymaserati** [pro-well-plan/well_profile#1]
The current assumption is that a list of dictionaries is imported.
https://github.com/pro-well-plan/well_profile/blob/37341284fa1f2fdd3ae8a5ad3899517dc3d1ccf1/well_profile/load_trajectory.py#L53
But if the code is being referenced from another python module it's likely that the data will be a list of lists, e.g.
```python
data = [md, inclination, azimuth, tvd]
```
This could be achieved by adding something like...
```python
if type(data[0]) is list:
    md, inc, azi, tvd = data
```
And this would be even nicer. Since you have pandas as a requirement already which is built on numpy, you're not really losing anything importing numpy.
```python
import numpy as np

if type(data[0]) is list or isinstance(data[0], np.ndarray):
    md, inc, azi, tvd = data
```

**Comment by jcamiloangarita** [comment]
that's a good addition, thanks @jonnymaserati. This will be added and a new version released.

**Comment by jcamiloangarita** [comment]
Data can be now a list of arrays using the version 0.4.1 (:
