### ISSUE TITLE
Exporting plot as HTML file

### ISSUE THREAD

**Issue by salsa360** [pro-well-plan/well_profile#19]
Hi Juan,

I have tried to export/save the 3D plot as an HTML file but to no avail.  Are you able to show me on how to save to HTML?

Thanks.
Kush

**Comment by jcamiloangarita** [comment]
Hi @salsa360,

The plot() method returns a plotly figure, so you can use the available features from that library. For example, for [exporting as HTML file](https://plotly.com/python/interactive-html-export/):
`well_fig = well.plot()`
`well_fig.write_html("path/to/file.html")`

**Comment by salsa360** [comment]
Hi Juan,

Thanks for your help.   Your code does work but it only saves one well in
the HTML file instead of saving all the different well trajectories in one
file.

It's strange because it does plot all wells in th browser window but only
saves on ewell to the HTML file.

Here is my code:

w1 = wp.load(source + filename1, set_start={'east':706060, 'north':1278609})
w2 = wp.load(source + filename2, set_start={'east':707719, 'north':1288232})
w3 = wp.load(source + filename3, set_start={'east':709772, 'north':1286507})
w4 = wp.load(source + filename4, set_start={'east':709744, 'north':1283920})
w5 = wp.load(source + filename5, set_start={'east':707399, 'north':1283469})
w6 = wp.load(source + filename6, set_start={'east':705696.25487,
'north':1280449.4031})
w7 = wp.load(source + filename7, set_start={'east':704983, 'north':1279975})

w_fig = w1.plot(add_well=[w2, w3, w4, w5, w6, w7],
            style={'darkMode': True, 'color': 'dls', 'size': 3},
                names=['CA-3 1A',
                       'CA-3 1B1',
                       'CA-3 1B2',
                       'CA-3 1B3',
                       'CA-3 1C1',
                       'CA-1',
                       'CA-2R1'
                      ]).show()        # Generate 3D plot

w_fig.write_html(dest + 'Notional Wells.html')


Best regards
Kush

**Comment by salsa360** [comment]
Hi Juan,

Disregard my earlier email.  The problem was with adding the ".show()"
snippet.  By removing it, then your code works OK.

Keep up your good work!


Best rgds
Kush
