### ISSUE TITLE
Coordinates slightly off

### ISSUE THREAD

**Issue by jonnymaserati** [pro-well-plan/well_profile#4]
Looks like there might be a discrepancy somewhere in the code since the Northing, Easting and TVD I get out from `well_profile` is slightly off the test data I checked the `welleng` and `wellpathpy` libraries against.

The other two libraries are generally within 10e-5 accuracy whereas `well_profile` is about 10e-1 (well, the 11th well at least which is the one I checked).

Here's the code I used to check the other two libraries, with a bit added on the bottom for generating `.csv` files (I was testing out the web app). You'll have to modify the code with the local paths set for your env. I've also attached the source data file, again which you'll need to change the path for.

Probably better to import the `well_profile` library and generate the surveys with that than using the web app, but I'll leave that yo you :-)

[standard-set-of-wellpaths-for-evaluating-clearance-scenarios-r4-17-may-2017.xlsx](https://github.com/pro-well-plan/well_profile/files/6108937/standard-set-of-wellpaths-for-evaluating-clearance-scenarios-r4-17-may-2017.xlsx)

```python
import wellpathpy
import welleng as we
import csv
from welleng.survey import Survey, SurveyHeader

# this is the ISCWSA dataset
filename = (
    "reference/standard-set-of-wellpaths"
    "-for-evaluating-clearance-scenarios-r4-17-may-2017.xlsx"
)

print("Loading data...")
try:
    data = we.io.import_iscwsa_collision_data(filename)
except:
    print(
        "Make sure you've updated filename to your local copy of ISCWSA's"
        " clearance scenarios"
    )

# Make a dictionary of surveys with welleng
print("Making surveys...")
surveys = {}
for well in data["wells"]:
    surveys[well] = {}
    sh = SurveyHeader(
        name=well,
        latitude=60.,
        b_total=50000.,
        dip=70.,
        declination=.0,
        convergence=0.,
        G=9.80665,
        azi_reference='grid'
    )
    if well == "Reference well":
        radius = 0.4572
    else:
        radius = 0.3048

    s = Survey(
        md=data["wells"][well]["MD"],
        inc=data["wells"][well]["IncDeg"],
        azi=data["wells"][well]["AziDeg"],
        deg=True,
        unit="meters"
    )
    surveys[well]['survey'] = s

    surveys[well]['errors'] = {
        'tvd': data["wells"][well]["TVD"] - s.tvd,
        'n': data["wells"][well]["N"] - s.n,
        'e': data["wells"][well]["E"] - s.e,
    }

# make a dictionary of wells with wellpathpy
surveys_wellpathpy = {}
for well in data['wells']:
    tvd, northing, easting, dls = wellpathpy.mincurve.minimum_curvature(
        md=data["wells"][well]["MD"],
        inc=data["wells"][well]["IncDeg"],
        azi=data["wells"][well]["AziDeg"],
    )

    surveys_wellpathpy[well] = {
        'tvd': tvd,
        'n': northing,
        'e': easting,
        'dls': dls,
        'errors_base': {
            'tvd': data["wells"][well]["TVD"] - tvd,
            'n': data["wells"][well]["N"] - northing,
            'e': data["wells"][well]["E"] - easting,
        },
        'errors_welleng': {
            'tvd': surveys[well]["survey"].tvd - tvd,
            'n': surveys[well]["survey"].n - northing,
            'e': surveys[well]["survey"].e - easting,
        }
    }

# generate a csv files to import into PWP web app
for well in data["wells"]:
    s_out = [['md', 'inc', 'azi']]
    s_out.extend([
        [md, inc, azi]
        for md, inc, azi in zip(
            data["wells"][well]["MD"],
            data["wells"][well]["IncDeg"],
            data["wells"][well]["AziDeg"],
        )
    ])

    with open(f'{well}.csv', 'w') as csv_file:
        writer = csv.writer(csv_file)
        for row in s_out:
            writer.writerow(row)

print("Done")

```

**Comment by jcamiloangarita** [comment]
Hi @jonnymaserati, thanks for the feedback. 

I've checked the 11th well and what happened was that there's a parameter which force the trajectory data to be equidistant and this was disabled by default. On the latest version of well_profile this was enabled by default and didn't changed this on the web-app. When forcing the entire wellpath to have **n**  number of equidistant points, then some differential is introduced within the results (that's of course something to improve) and probably getting only two same MD points to compare, surface and target.

Going back to the point, I've disabled this parameter (_equidistant_) as default. Checked after this change and got exactly the same points as shown in the dataset. Please try yourself and let me know (:

<img width="393" alt="Screenshot 2021-03-10 at 09 04 49" src="https://user-images.githubusercontent.com/52009346/110596509-adb3bf00-817f-11eb-953e-fc4377444e99.png">

<img width="593" alt="Screenshot 2021-03-09 at 17 35 54" src="https://user-images.githubusercontent.com/52009346/110504899-ea3ed680-80fd-11eb-84d2-cfaaf7c13e42.png">
