### ISSUE TITLE
Units not plotting in english

### ISSUE THREAD

**Issue by ndenzin** [pro-well-plan/well_profile#9]
Hi there! I love what you guys are doing at Pro Well Plan.  I am a senior drilling engineer in the USA and a very very novice programmer, still trying to get through CS50x, so please excuse me if this is a mistake on my end... A couple of issues I noticed with the units input:  On the examples in the documentation, the argument for well_profile.get() is titled "units".  However, when the program is run, there is an error with the argument "units".  When I change that argument to "set_info", I can get the program to plot.  However, if the "set_info" value is changed to 'english', it still plots metric units.  

![image](https://user-images.githubusercontent.com/78862706/125714283-80c17e12-a0cd-4deb-9180-9b73b068c2e8.png)

**Comment by jcamiloangarita** [comment]
Hi @ndenzin,

We're glad you like our open-source initiative. You are right, the latest versions of `well_profile` have introduced the argument `set_info` to deal with different settings such as `dlsResolution`, `wellType` and `units`, but the documentation was not updated.

We have now updated the [documentation](https://well-profile.readthedocs.io/en/latest/create_profile.html#horizontal-single-curve-well) and now it shows the correct way on the latest version to define the system of units.
A quick example:
> import well_profile as wp 
>w1 = wp.get(1000, profile='V', set_info={'dlsResolution': 100, 'units': 'english'})
>w1.plot().show()
<img width="483" alt="Screenshot 2021-07-15 at 10 11 05" src="https://user-images.githubusercontent.com/52009346/125753116-8d4a9714-d2ef-43e7-bc09-03abda92a7c4.png">

Thank you for your feedback. In this way it's much easier to continue improving these projects within the open-source community. Looking forward to hearing more from you.
